comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null
ignore:
  - app/db.py
  - app/definitions.py
  - app/log_config.py
  - app/main.py
