services:
  metrics_service:
    image: metrics_service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    tty: true