# METRICS ACTIONS

TRAINING_SERVICE = "training-service"
USER_SERVICE = "user-service"
USER_EDIT = "user_edit"
SIGNUP = "signup"
GOOGLE_SIGNUP = "google_signup"
BLOCK = "block"
UNBLOCK = "unblock"
LOGIN = "login"
GOOGLE_LOGIN = "google_login"
PASSWORD_EDIT = "password_reset"
NEW_TRAINING = "new_training"
DELETE_TRAINING = "delete_training"
MEDIA_UPLOAD = "media_upload"
ADD_TRAINING_TO_FAVS = "add_training_to_favs"
REMOVE_TRAINING_FROM_FAVS = "remove_training_from_favs"
